services:
  app:
    build: .
    container_name: yggdrasil-service
    restart: unless-stopped
    ports:
      - "8090:8080"
    volumes:
      - ../DataStorage/calendar:/data/calendar/
      - ../DataStorage/users/users.csv:/data/users/users.csv
